### ISSUE TITLE
for loop to terminate

### ISSUE THREAD

**Issue by akshayrf12345** [cloudmesh/cloudmesh-pi-burn#10]
loop to terminate after X seconds exit with error n=5

**Comment by laszewsk** [comment]
This task was not completed and needs to be reevaluated.

**Comment by laszewsk** [comment]
This seems to indicate a major bug in the program

**Comment by rickotten** [comment]
Which for loop are we talking about?

**Comment by laszewsk** [comment]
I think you get it, the error is not properly described, so we will see what happens when we run it.
