### ISSUE TITLE
name of burner pi

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-burn#17]
@Richard Otten I like that you simplify the documentation at https://github.com/cloudmesh/cloudmesh-pi-burn
and use for the PI for burning just the name “raspberry” which is the default or “burnpi” instead of red which we used for the master. We just use the simplified setup where everyone gets one more SDCard. We still keep the description as is that one could overwrite the master pi last.

**Comment by rickotten** [comment]
Starting this now...

**Comment by laszewsk** [comment]
i can join in 10 minutes

**Comment by laszewsk** [comment]
RIchie (I cc Anthony as he also contributed the benchmark): 

Super urgent task …

could we engage in a live hacking session for the cm-pi-burn program documentation only. 

I noticed I lost track where all the documenation is or where the best documentation is. It looks like its not in cm-pi-burn and due to me insiting that old documentation is maintained we lost realy track wher ethe documentation is.

Can you send me the link to the newest documenatation so i can prepare the meeting with you.

I see a couple too many attempts to do the documentation (my fault!) as I have not kept up with what has been done by you and did not organize this properly with you.

https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/README.md
https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/README-old.md
https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/cm-pi-burn.md
https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/notes.md
https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/paper/vonLaszewski-cmburn.md
https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/docs/vonLaszewski-cmburn.pdf (generated from previous file, does no longer work for me to generate it with make)

https://cloudmesh.github.io/cloudmesh-manual/projects/project-pi-burn.html?highlight=burn
which is generated from
https://github.com/cloudmesh/cloudmesh-manual/blob/main/manual/docs-source/source/projects/project-pi-burn.rst 

We also have the bridge command at

https://github.com/cloudmesh/cloudmesh-pi-cluster/blob/main/README.md
and 
https://github.com/cloudmesh/cloudmesh-pi-cluster/blob/main/cloudmesh/bridge/README.md 


New 

(start of new components for cluster, Gregor)

https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/README-parts.md

benchmarks from Anthony
https://github.com/cloudmesh/cloudmesh-pi-cluster/blob/main/cloudmesh/sd-card/benchmarks.md

**Comment by rickotten** [comment]
Now is not the best time for me to have a voice chat as there is some loud
maintenance taking place on the roof of my apartment. Perhaps later today
when they are finished and I have more work to show?

-Richie

**Comment by laszewsk** [comment]
ok. le me know when its better for you. 
All content that is supposed to be deleted is to be preserved in README-old.md. If however it stys in README.md you do not have to copy it int README.old

**Comment by asurirk** [comment]
Richie, I would like to join if it's after 5 pm.
