### ISSUE TITLE
burn: ubuntu/rasbian:  verify if temp command works after burning

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-burn#40]
I have merged the ubuntu branch into main. This requires a quality control check of burning an (at minimum) 3 node cluster. YOu can follow the appropriate tutorial. If such a tutorial does not exist on piplanet.org in tutorials, please create. If you see issues, report and or correct

[ Y] Richard MacOS
[Y ] Anthiny Linux
[ Y] Rama Pi
[ ] DK Pi

related to #28 and #30

**Comment by jpfleischer** [comment]
related to #28 and #30

**Comment by laszewsk** [comment]
reassigned to JP.
just follow tutorial and if works, let us know so we can close this
