### ISSUE TITLE
windows: possible python error in regexp

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-burn#57]
analyse if the code inspect error is a real issue in windows

windowssdcard.py: invalid escape secence \s
line 502, 509

**Comment by jpfleischer** [comment]
there is no error upon running the program in windows (`python windowssdcard.py`) however we can get rid of the code inspect error by prefixing r as in #58

**Comment by jpfleischer** [comment]
fixed with this commit https://github.com/cloudmesh/cloudmesh-pi-burn/commit/802c6f7a2e952364083783b4d45c85f7d633461d
